name: Sync to Gitee

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: QinHongZhe/test-clone
          dst: deligense/test-clone
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          clone_style: "https"
          #uses: wearerequired/git-mirror-action@master
          #env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          #    SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          #with:
          # 注意替换为你的 GitHub 源仓库地址
          #    source-repo: "git@github.com:test-clone.git"
        # 注意替换为你的 Gitee 目标仓库地址
        #    destination-repo: "git@gitee.com:deligense/test-clone.git"
